environment:
    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python27-x64"
        - PYTHON: "C:\\Python33"
          DISTUTILS_USE_SDK: "1"
        - PYTHON: "C:\\Python33-x64"
          DISTUTILS_USE_SDK: "1"
        - PYTHON: "C:\\Python34"
          DISTUTILS_USE_SDK: "1"
        - PYTHON: "C:\\Python34-x64"
          DISTUTILS_USE_SDK: "1"
        - PYTHON: "C:\\Python35"
        - PYTHON: "C:\\Python35-x64"
        - PYTHON: "C:\\Python36"
        - PYTHON: "C:\\Python36-x64"
          RUN_FLAKE: "1"

install:
    - "%PYTHON%\python.exe -m pip install wheel"
    - "%PYTHON%\python.exe setup.py develop"

build: off

test_script:
    - "%PYTHON%\python.exe ttasks.py test"

after_build:
    - "%PYTHON\python.exe setup.py bdist_wheel"

artifacts:
    - path: dist\*
